import type { Metadata } from "next";
import Link from "next/link";
import { getPublishedContent } from "@/lib/content";

export const metadata: Metadata = { title: "Events", description: "Discover ways to meet, learn and make memories together." };
function dateLabel(value?: string | null) { if (!value) return "Date coming soon"; return new Date(value).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}); }
export default async function EventsPage() {
  const all = await getPublishedContent("event",64); const now = new Date();
  const upcoming = all.filter((event)=>!event.starts_at || new Date(event.ends_at || event.starts_at)>=now); const past = all.filter((event)=>event.starts_at && new Date(event.ends_at || event.starts_at)<now);
  return <div className="library-page page-shell"><div className="page-intro"><span className="eyebrow eyebrow-line">The best parts happen together</span><h1>Come <em>together.</em></h1><p>Find your people, share a moment, and make a memory that feels like yours.</p></div><section className="event-discovery"><div className="section-heading"><div><span className="eyebrow">Save a spot for something good</span><h2>Coming up</h2></div></div>{upcoming.length ? <div className="event-cards">{upcoming.map((event,index)=><article className="event-card" key={event.id}><Link href={`/content/${event.slug}`} className="event-image">{event.cover_url ? <img src={event.cover_url} alt="" loading="lazy"/> : <span>✳</span>}<span className="event-card-index">0{index+1}</span></Link><div className="event-card-copy"><span className="eyebrow muted">{event.category || "Teens2Inspire gathering"}</span><h3><Link href={`/content/${event.slug}`}>{event.title}</Link></h3><div className="event-detail-line">{dateLabel(event.starts_at || event.published_at)}{event.location && <span> · {event.location}</span>}</div>{event.description && <p>{event.description}</p>}<Link className="text-link" href={event.external_url || `/content/${event.slug}`}>Event details <span>↗</span></Link></div></article>)}</div> : <div className="empty-library"><span className="empty-sparkle">✳</span><h2>A gathering is in the making.</h2><p>We’ll share the details here as soon as the next event is ready.</p></div>}</section>{past.length>0 && <section className="event-discovery past-events"><div className="section-heading"><div><span className="eyebrow">Memories we made</span><h2>Past events</h2></div></div><div className="past-event-list">{past.map((event)=><Link className="past-event-row" href={`/content/${event.slug}`} key={event.id}><span>{dateLabel(event.starts_at)}</span><b>{event.title}</b><i>↗</i></Link>)}</div></section>}</div>;
}
